### ISSUE TITLE
`cargo test` failed

### ISSUE THREAD

**Issue by lengyijun** [sybila/biodivine-lib-bdd#16]
Could you please fix them?

**Comment by daemontus** [comment]
Absolutely. I am AFK today, but I'll have a look tomorrow/Friday. The repo needs to be migrated from Travis to Github Actions anyway :)

**Comment by daemontus** [comment]
Sorry, for the inconvenience, `cargo test` should work now as expected :) 

The problem was not with correctness of the code, but rather that some tests relied on checks which we only enabled with a special feature enabled (to avoid perf. penalty in production, but to also to be able to enable the checks regardless of other debug assertions). In retrospect, this will be better served by `debug_assert!`, at least for now. So the assertions should be standard now and the problematic tests have been marked as debug only.

This should close the issue. However, if you still have problems feel free to comment and I'll reopen it.
